name: Manually Deploy LW CT/CF
# TODO: Leverage Terraform backend maintenance of state file (https://www.terraform.io/docs/language/settings/backends/s3.html)
# Controls when the action will run. 
on:
  repository_dispatch:
    types: [create]
  workflow_dispatch:
    inputs:
      MAN_AWS_REGION:
        description: 'AWS Region to deploy in'
        default: 'us-east-1'
        required: true
      MAN_AWS_ACCESS_KEY_ID: 
        description: 'Your AWS Access Key'
        default: 'XXXXXXXXXXXXXXXXXXXX'
        required: true
      MAN_AWS_SECRET_ACCESS_KEY: 
        description: 'Your AWS Secret'
        default: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
        required: true
      MAN_LW_API_KEY_ID:
        description: 'Your Lacework API KeyId'
        default: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
        required: true
      MAN_LW_API_SECRET:
        description: 'Your Lacework API Secret'
        default: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
        required: true
      MAN_LW_ACCOUNT:
        description: 'Your Lacework Account'
        default: 'XXXXXXXXXX'
        required: true
               
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deployLW:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Mask up
        run: |
          MAN_AWS_REGION_SECRET=$(jq -r '.inputs.MAN_AWS_REGION' $GITHUB_EVENT_PATH)
          MAN_AWS_ACCESS_KEY_ID_SECRET=$(jq -r '.inputs.MAN_AWS_ACCESS_KEY_ID' $GITHUB_EVENT_PATH)
          MAN_AWS_SECRET_ACCESS_KEY_SECRET=$(jq -r '.inputs.MAN_AWS_SECRET_ACCESS_KEY' $GITHUB_EVENT_PATH)
          MAN_LW_API_KEY_ID_SECRET=$(jq -r '.inputs.MAN_LW_API_KEY_ID' $GITHUB_EVENT_PATH)
          MAN_LW_API_SECRET_SECRET=$(jq -r '.inputs.MAN_LW_API_SECRET' $GITHUB_EVENT_PATH)
          MAN_LW_ACCOUNT_SECRET=$(jq -r '.inputs.MAN_LW_ACCOUNT' $GITHUB_EVENT_PATH)
          
          
          echo ::add-mask::$MAN_AWS_REGION
          echo ::add-mask::$MAN_AWS_ACCESS_KEY_ID
          echo ::add-mask::$MAN_AWS_SECRET_ACCESS_KEY
          echo ::add-mask::$MAN_LW_API_KEY_ID
          echo ::add-mask::$MAN_LW_API_SECRET
          echo ::add-mask::$MAN_LW_ACCOUNT

      
      
      

      # Runs a single command using the runners shell
      - name: download Lacework CLI
        run: |
          curl https://raw.githubusercontent.com/lacework/go-sdk/main/cli/install.sh -O

      - name: Run lacework installer
        run: |
          sudo chmod +x install.sh
          sudo ./install.sh
          lacework version
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: = ${{ MAN_AWS_ACCESS_KEY_ID_SECRET }}
          aws-secret-access-key: ${{ MAN_AWS_SECRET_ACCESS_KEY_SECRET }}
          aws-region: ${{ MAN_AWS_REGION_SECRET }}
          
          #aws-access-key-id: ${{ github.event.inputs.MAN_AWS_ACCESS_KEY_ID }}
          #aws-secret-access-key: ${{ github.event.inputs.MAN_AWS_SECRET_ACCESS_KEY }}
          #aws-region: ${{ github.event.inputs.MAN_AWS_REGION }}

#      - name: Do the THING
#        env:
#          LW_API_KEY: ${{ github.event.inputs.MAN_LW_API_KEY_ID }}
#          LW_API_SECRET: ${{ github.event.inputs.MAN_LW_API_SECRET }}
#          LW_ACCOUNT: ${{ github.event.inputs.MAN_LW_ACCOUNT }}
#        run: | 
#          terraform init
#          terraform apply --auto-approve
          