name: Manually Deploy LW CT/CF
# TODO: Leverage Terraform backend maintenance of state file (https://www.terraform.io/docs/language/settings/backends/s3.html)
# Controls when the action will run. 
on:
  repository_dispatch:
    types: [create]
  workflow_dispatch:
    inputs:
      AWS_REGION:
        description: 'AWS deploy region'
        default: 'us-east-1'
        required: true
      AWS_ACCESS_KEY_ID: 
        description: 'Your AWS Access Key'
        default: '<your key>'
        required: true
      AWS_SECRET_ACCESS_KEY: 
        description: 'Your AWS Secret'
        default: '<your secret>'
        required: true
      LW_API_KEY_ID:
        description: 'Your Lacework API KeyId'
        default: '<your LW Key>'
        required: true
      LW_API_SECRET:
        description: 'Your Lacework API Secret'
        default: '<your LW secret>'
        required: true
      LW_ACCOUNT:
        description: 'Your Lacework Account'
        default: '<your account name>'
        required: true
               
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deployLW:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 
        uses: actions/checkout@v2


#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ github.event.inputs.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ github.event.inputs.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ github.event.inputs.AWS_REGION }}

      # Runs a single command using the runners shell
      - name: download Lacework CLI
        run: |
          curl https://raw.githubusercontent.com/lacework/go-sdk/main/cli/install.sh -O

      - name: Run lacework installer
        run: |
          sudo chmod +x install.sh
          sudo ./install.sh
          lacework version
      
      - name: Do the THING
        env:
          LW_API_KEY: ${{ github.event.inputs.LW_API_KEY_ID }}
          LW_API_SECRET: ${{ github.event.inputs.LW_API_SECRET }}
          LW_ACCOUNT: ${{ github.event.inputs.LW_ACCOUNT }}
          AWS_ACCESS_KEY_ID: ${{ github.event.inputs.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ github.event.inputs.AWS_REGION }}
        run: | 
          terraform init
          terraform apply --auto-approve
          