name: Dyna-Issue
# TODO: Create clever naming convention for tfstate file
# Controls when the action will run. 
on:
  issues: 
    types: [labeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"a
  InformMatt:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Close the loop
        if: ${{ github.event.label.name == 'Text This to Matt C' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Matt has been texted :sparkles:
            > ${{ github.event.issue.body }}

      - name: Respond to the issue
        if: ${{ github.event.label.name != 'Text This to Matt C' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            I see you've applied the _${{ github.event.label.name }} label.  Great job! 

      - name: 'Sending SMS Notification'
        if: ${{ github.event.label.name == 'Text This to Matt C' }}
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: '+19014575769'
          toPhoneNumber: '${{ secrets.MATTS_NUMBER }}'
          message: "${{ github.event.issue.body }}  \n\n ${{ github.event.issue.html_url }}"
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}