name: Dyna-Issue
# TODO: Create clever naming convention for tfstate file
# Controls when the action will run. 
on:
  issues: 
    types: [labeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"a
  InformMatt:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Close the loop
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Matt has been texted :sparkles:
            > ${{ github.event.issue.body }}

      - name: Build message
        run: | 
          echo "${{ github.event.issue.body }} \n ${{ github.event.issue.url }}"
        