name: LW Inline Scan
# TODO: Leverage Terraform backend maintenance of state file (https://www.terraform.io/docs/language/settings/backends/s3.html)
# Controls when the action will run. 
on:
  repository_dispatch:
    types: [scan]
  workflow_dispatch:
    inputs:
      AWS_NAME: 
        description: 'This is a fake parameter'
        default: 'who cares, its fake'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Build the latest Docker image
        run: docker build . -t bryancross:test-image
  
      - name: Download lw-scanner
        run: |
          sudo curl -LJO https://github.com/lacework/lacework-vulnerability-scanner/releases/download/v0.1.2/lw-scanner-linux-amd64
          sudo mv lw-scanner-linux-amd64 lw-scanner
          sudo chmod +x lw-scanner

      - name: Scan image
        env: 
          LW_ACCOUNT_NAME: lwintbryancross
          LW_ACCESS_TOKEN: _67d888a3d3482667c13e49f57c6b6aa4
        run: | 
          ./lw-scanner evaluate bryancross test-image 