name: Lacework-Deploy CT and Config
# TODO: Leverage Terraform backend maintenance of state file (https://www.terraform.io/docs/language/settings/backends/s3.html)
# Controls when the action will run. 
on:
  repository_dispatch:
    types: [create]
  workflow_dispatch:
    inputs:
      AWS_NAME: 
        description: 'This is a fake parameter'
        default: 'who cares, its fake'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deployLW:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: download Lacework CLI
        run: |
          curl https://raw.githubusercontent.com/lacework/go-sdk/main/cli/install.sh -O

      - name: Run lacework installer
        run: |
          sudo chmod +x install.sh
          sudo ./install.sh
          lacework version

jobs:
  build:
    name: Build and Scan
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag pjlamb12/angular-cli:${{steps.vars.outputs.tag}}
      
      - name: Push the tagged Docker image
        run: docker push pjlamb12/angular-cli:${{steps.vars.outputs.tag}}
      
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag pjlamb12/angular-cli:latest
      
      - name: Push the latest Docker image
        run: docker push pjlamb12/angular-cli:latest
  
      - name: Download lw-scanner
        run: |
          sudo curl -LJO https://github.com/lacework/lacework-vulnerability-scanner/releases/download/v0.1.2/lw-scanner-linux-amd64
          sudo mv lw-scanner-linux-amd64 lw-scanner
          sudo chmod +x lw-scanner

      - name: Scan image
        run: ./lw-scanner evaluate $REPO/$IMAGE $GITHUB_SHA -v=false | jq -e '.fixable_vulnerabilities == 0, .critical_vulnerabilities == 0, .high_vulnerabilities ==0'