name: Break me
# TODO: Leverage Terraform backend maintenance of state file (https://www.terraform.io/docs/language/settings/backends/s3.html)
# Controls when the action will run. 
on:
  repository_dispatch:
    types: [scan]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Break:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Check for vulns
        id: vuln-check
        run: | 
        echo ::set-output name=vulns::$VULNS
        

      -name: We broke?
       if: ${( steps.vuln-check.outputs.vulns > 0)}
       uses: actions/github-script@v3
       with:
         script: | 
           core.setFailed('Holy shit!')