name: Test Core
# TODO: Leverage Terraform backend maintenance of state file (https://www.terraform.io/docs/language/settings/backends/s3.html)
# Controls when the action will run. 
on:
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Check for vulns
        id: vuln-check
        run: | 
          export VULNS=$(jq .high_vulnerabilities $(find . -type f -name 'evaluation*'))

      - name: Output results
        if: ${{ steps.vuln-check.outputs.vulns > 0 }}
        run: | 
          echo "Build failed, for this container is FILTHY AF"
          echo "Details:"
          #This seems to be the only way to get the JQ output pretty printed
          jq -f message.jq $(find . -type f -name 'evaluation*') > results.json
          cat results.json

      - name: Fail if broken
        if: ${{ steps.vuln-check.outputs.vulns > 0 }}
        uses: actions/github-script@v3
        with:
          script: | 
            core.setFailed("Critical/High vulnerabilities found!")